/**
 * Brand-logo generator.
 *
 * Pulls SVG path data from `simple-icons` (3000+ brands) into a small bundled
 * data file — but ONLY for icons we actually reference, so the shipped bundle
 * stays lean while every icon simple-icons has is one slug away.
 *
 * Sources:
 *   1. every vendor recipe's `icon` slug (so a new vendor's logo ships automatically)
 *   2. a CATALOG of common billing/SaaS brands — pre-bundled so the future
 *      "browse vendors to add" gallery is instant, before the recipe even exists
 *
 * Catalog brands simple-icons doesn't carry are reported and omitted. A vendor
 * may opt into a letter avatar by omitting `icon`, but any declared vendor icon
 * must resolve through simple-icons or an explicit override.
 *
 *   npm run gen:icons
 */
import { writeFileSync } from "node:fs";
import { ALL_VENDORS } from "../src/vendors";
import { OVERRIDES } from "../src/vendors/icon-overrides";
import * as simpleIcons from "simple-icons";

// Popular billing/SaaS vendors to pre-bundle. Unknown slugs are skipped, so this
// list can be aspirational — add freely as the vendor library grows.
const CATALOG = [
  "stripe", "notion", "figma", "linear", "cloudflare", "googlecloud", "digitalocean",
  "netlify", "supabase", "planetscale", "mongodb", "sentry", "datadog", "postman",
  "gitlab", "atlassian", "jira", "asana", "zoom", "dropbox", "twilio", "hetzner",
  "render", "auth0", "okta", "hubspot", "intercom", "zendesk", "shopify", "fortnox",
  "adobe", "canva", "miro", "airtable", "clickup", "loom", "calendly", "typeform",
];

interface SimpleIcon { title: string; slug: string; hex: string; path: string }

const bySlug = new Map<string, SimpleIcon>();
for (const key of Object.keys(simpleIcons)) {
  const icon = (simpleIcons as Record<string, SimpleIcon>)[key];
  if (icon && icon.slug) bySlug.set(icon.slug, icon);
}

const wanted = new Set<string>();
const vendorIconSlugs = new Set<string>();
for (const v of ALL_VENDORS) {
  if (!v.icon) continue;
  wanted.add(v.icon);
  vendorIconSlugs.add(v.icon);
}
for (const slug of CATALOG) wanted.add(slug);

const out: Record<string, { path: string; hex: string; title: string }> = {};
const missing: string[] = [];
for (const slug of [...wanted].sort()) {
  // Overrides win (real marks for brands simple-icons dropped), then simple-icons.
  const override = OVERRIDES[slug];
  const icon = bySlug.get(slug);
  if (override) out[slug] = override;
  else if (icon) out[slug] = { path: icon.path, hex: `#${icon.hex}`, title: icon.title };
  else missing.push(slug);
}

const missingVendorIcons = missing.filter((slug) => vendorIconSlugs.has(slug));
if (missingVendorIcons.length > 0) {
  throw new Error(
    `Declared vendor icons do not resolve; omit icon for an intentional letter avatar or add an override: ${missingVendorIcons.join(", ")}`,
  );
}

const file =
  `// AUTO-GENERATED by scripts/build-icons.ts — do not edit by hand.\n` +
  `// Brand logos from simple-icons (${bySlug.size} available). Refresh: npm run gen:icons\n\n` +
  `export interface BrandIcon {\n  /** 24×24 SVG path data. */\n  path: string;\n  /** Official brand colour, e.g. "#181717". */\n  hex: string;\n  title: string;\n}\n\n` +
  `export const ICONS: Record<string, BrandIcon> = ${JSON.stringify(out, null, 2)};\n`;

writeFileSync(new URL("../src/vendors/icons.generated.ts", import.meta.url), file);

const usedByVendors = ALL_VENDORS.filter((v) => v.icon && out[v.icon]).length;
console.log(
  `✓ ${Object.keys(out).length} brand icons generated (${usedByVendors}/${ALL_VENDORS.length} production and experimental vendors + catalog).`,
);
if (missing.length) console.log(`  unresolved optional catalog icons omitted: ${missing.join(", ")}`);
