#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
SESSION_FILE="artifacts/live/session.json"
RESULT_FILE="artifacts/live/results.tsv"

[[ -f "$SESSION_FILE" ]] || {
  printf 'Run npm run prepare:live-supplier-test -- --browser chrome first.\n' >&2
  exit 1
}

EXTENSION_PATH=$(node -e 'const s=require("./artifacts/live/session.json"); process.stdout.write(s.extensionPath)')
EXPECTED_RUNTIME=$(node -e 'const s=require("./artifacts/live/session.json"); process.stdout.write("v"+s.collectorVersion+" discovery-engine="+s.discoveryEngine+" document-acquisition="+s.documentAcquisition)')
EXPECTED_CHUNK=$(node -e 'const s=require("./artifacts/live/session.json"); process.stdout.write(s.serviceWorkerChunk.split("/").pop())')

banner "Ratatosk live supplier test"

stage "Reload the exact unpacked build"
say "Use the prepared package only:"
note "$EXTENSION_PATH"
open_url "chrome://extensions/"
step "Find Ratatosk — Invoice Collector. If it is absent, choose Load unpacked and select the folder above."
step "Click Reload once. Do not select a ZIP."
pause "Reloaded?"

stage "Verify runtime identity"
say "Expected service-worker identity:"
note "$EXPECTED_RUNTIME"
note "$EXPECTED_CHUNK"
step "On Ratatosk's extension card, open the Service worker console."
step "Reload the extension once if no ready line is visible, then copy the complete [collector] ready line."
ask RUNTIME_LINE "Paste the ready line:"
[[ "$RUNTIME_LINE" == *"$EXPECTED_RUNTIME"* && "$RUNTIME_LINE" == *"$EXPECTED_CHUNK"* ]] || {
  printf '  %s✗ runtime or service-worker chunk does not match the prepared build%s\n' "$RED" "$RESET"
  exit 1
}
printf '  %s✓ runtime identity matched%s\n' "$GREEN" "$RESET"

stage "Approve the supplier tabs"
step "List the hostnames of the supplier tabs already open and signed in."
step "Use comma-separated hostnames only — no paths, query strings, account names, or invoice data."
ask SUPPLIER_HOSTS "Supplier hostnames:"
IFS=',' read -r -a HOSTS <<< "$SUPPLIER_HOSTS"
: > "$RESULT_FILE"
: > "artifacts/live/approved-hosts.txt"
for raw in "${HOSTS[@]}"; do
  host=$(printf '%s' "$raw" | tr '[:upper:]' '[:lower:]' | xargs)
  [[ "$host" =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$ ]] || {
    warn "invalid hostname: $host"
    exit 1
  }
  printf '%s\n' "$host" >> "artifacts/live/approved-hosts.txt"
done
sort -u "artifacts/live/approved-hosts.txt" -o "artifacts/live/approved-hosts.txt"

stage "Run the bounded supplier matrix"
printf 'hostname\tfamily\tdestination\tdiscovery\tboundary\tfirst_status\tfirst_accepted\tfirst_actions\tfirst_ledger\tdestination_readback\timmediate_accepted\timmediate_actions\timmediate_ledger\tcadence_accepted\tcadence_actions\tcadence_ledger\tpage_owned_downloads\tresult\n' > "$RESULT_FILE"
while IFS= read -r host; do
  say "Supplier: $host"
  step "Switch to the already-open tab for this hostname."
  step "Open Ratatosk and select Find Invoices. Wait for preview or a terminal failure."
  ask OUTCOME "Enter preview, failed, or blocked:"
  [[ "$OUTCOME" =~ ^(preview|failed|blocked)$ ]] || { warn "invalid outcome"; exit 1; }
  BOUNDARY="none"
  if [[ "$OUTCOME" == "failed" ]]; then
    step "From the sanitized log or report, copy only result@phase/result (for example list_failed@menu_reveal/not_present)."
    ask BOUNDARY "Closed first boundary:"
    [[ "$BOUNDARY" =~ ^[a-z_]+(@[a-z_]+/[a-z_]+)?$ ]] || { warn "invalid closed boundary"; exit 1; }
    printf '%s\tna\tna\tfailed\t%s\tna\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\tfailed\n' "$host" "$BOUNDARY" >> "$RESULT_FILE"
    continue
  fi
  if [[ "$OUTCOME" == "blocked" ]]; then
    printf '%s\tna\tna\tblocked\tmanual_handoff\tna\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\tblocked\n' "$host" >> "$RESULT_FILE"
    continue
  fi

  ask SUPPLIER_FAMILY "Family (opaque_semantic_spa, server_rendered_documents, or structured_api):"
  [[ "$SUPPLIER_FAMILY" =~ ^(opaque_semantic_spa|server_rendered_documents|structured_api)$ ]] || { warn "invalid supplier family"; exit 1; }
  ask DESTINATION_KIND "Destination kind (filesystem or igdrasil):"
  [[ "$DESTINATION_KIND" =~ ^(filesystem|igdrasil)$ ]] || { warn "invalid destination kind"; exit 1; }
  step "Choose that destination in Ratatosk, then select Connect & Collect."
  step "When the run ends, use only its sanitized status and numeric counts; do not copy invoice data."
  ask FIRST_STATUS "First status (ok, partial, or failed):"
  [[ "$FIRST_STATUS" =~ ^(ok|partial|failed)$ ]] || { warn "invalid first status"; exit 1; }
  if [[ "$FIRST_STATUS" == "failed" ]]; then
    ask BOUNDARY "Closed first boundary:"
    [[ "$BOUNDARY" =~ ^[a-z_]+(@[a-z_]+/[a-z_]+)?$ ]] || { warn "invalid closed boundary"; exit 1; }
    printf '%s\t%s\t%s\tpreview\t%s\tfailed\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\tfailed\n' "$host" "$SUPPLIER_FAMILY" "$DESTINATION_KIND" "$BOUNDARY" >> "$RESULT_FILE"
    continue
  fi
  ask FIRST_ACCEPTED "First-run accepted documents:"
  ask FIRST_ACTIONS "First-run semantic actions:"
  ask FIRST_LEDGER "First-run extension ledger delta:"
  ask DESTINATION_READBACK "First-run destination readback count:"
  [[ "$FIRST_ACCEPTED" =~ ^[0-9]{1,5}$ && "$FIRST_ACTIONS" =~ ^[0-9]{1,5}$ && "$FIRST_LEDGER" =~ ^[0-9]{1,5}$ && "$DESTINATION_READBACK" =~ ^[0-9]{1,5}$ ]] || { warn "counts must be integers from 0 to 99999"; exit 1; }

  step "Run this connected supplier again immediately."
  ask IMMEDIATE_ACCEPTED "Immediate accepted documents:"
  ask IMMEDIATE_ACTIONS "Immediate semantic actions:"
  ask IMMEDIATE_LEDGER "Immediate ledger delta:"
  [[ "$IMMEDIATE_ACCEPTED" =~ ^[0-9]{1,5}$ && "$IMMEDIATE_ACTIONS" =~ ^[0-9]{1,5}$ && "$IMMEDIATE_LEDGER" =~ ^[0-9]{1,5}$ ]] || { warn "counts must be integers from 0 to 99999"; exit 1; }

  step "In the Ratatosk service-worker console, run: chrome.alarms.create('collector-sync', { when: Date.now() + 1000 })"
  step "Wait for the scheduled run to finish, then read the same sanitized counts."
  ask CADENCE_ACCEPTED "Cadence accepted documents:"
  ask CADENCE_ACTIONS "Cadence semantic actions:"
  ask CADENCE_LEDGER "Cadence ledger delta:"
  ask PAGE_OWNED_DOWNLOADS "Unexpected page-owned downloads across all three runs:"
  [[ "$CADENCE_ACCEPTED" =~ ^[0-9]{1,5}$ && "$CADENCE_ACTIONS" =~ ^[0-9]{1,5}$ && "$CADENCE_LEDGER" =~ ^[0-9]{1,5}$ && "$PAGE_OWNED_DOWNLOADS" =~ ^[0-9]{1,5}$ ]] || {
    warn "counts must be integers from 0 to 99999"
    exit 1
  }

  MATRIX_RESULT="failed"
  if (( FIRST_ACCEPTED > 0 && FIRST_LEDGER == FIRST_ACCEPTED && DESTINATION_READBACK == FIRST_ACCEPTED && IMMEDIATE_ACCEPTED == 0 && IMMEDIATE_ACTIONS == 0 && IMMEDIATE_LEDGER == 0 && CADENCE_ACCEPTED == 0 && CADENCE_ACTIONS == 0 && CADENCE_LEDGER == 0 && PAGE_OWNED_DOWNLOADS == 0 )); then
    MATRIX_RESULT="pass"
  elif (( FIRST_ACCEPTED == 0 )); then
    MATRIX_RESULT="blocked_preexisting_history"
  fi
  printf '%s\t%s\t%s\tpreview\tnone\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$host" "$SUPPLIER_FAMILY" "$DESTINATION_KIND" "$FIRST_STATUS" "$FIRST_ACCEPTED" "$FIRST_ACTIONS" \
    "$FIRST_LEDGER" "$DESTINATION_READBACK" "$IMMEDIATE_ACCEPTED" "$IMMEDIATE_ACTIONS" "$IMMEDIATE_LEDGER" \
    "$CADENCE_ACCEPTED" "$CADENCE_ACTIONS" "$CADENCE_LEDGER" \
    "$PAGE_OWNED_DOWNLOADS" "$MATRIX_RESULT" >> "$RESULT_FILE"
  printf '  %s✓ recorded privacy-safe end-to-end outcome: %s%s\n' "$GREEN" "$MATRIX_RESULT" "$RESET"
done < "artifacts/live/approved-hosts.txt"

finish
note "Sanitized session results: $RESULT_FILE"
